name: Build ZMK firmware
on:
  workflow_dispatch:
  push:
    paths-ignore:
      - "keymap-drawer/**"

jobs:
  build:
    # Pin workflow to pre-Zephyr 4.1 version (Dec 6, 2025)
    # Matches ZMK version pinned in config/west.yml
    uses: zmkfirmware/zmk/.github/workflows/build-user-config.yml@83eafcbf9b12226f1d0dbb30a77e6ddc332a4210

